name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Certifique-se de usar a mesma versão do Node.js que seu projeto utiliza

    - name: Install dependencies for backend
      working-directory: ./api
      run: npm install

    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: npm install

    - name: Install Cypress dependencies
      working-directory: ./test
      run: npm install

    - name: Start backend
      working-directory: ./backend
      run: npm start &
      
    - name: Start frontend
      working-directory: ./frontend
      run: npm run serve &
    
    - name: Wait for services to be up
      run: sleep 30s  # Ajuste o tempo conforme necessário para garantir que os serviços estejam prontos

    - name: Run Cypress tests
      working-directory: ./test
      run: npm run cypress:run
